# Generated by Django 5.1.6 on 2025-03-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_blog_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
